In [21]:
#import relevent libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
print("Libraries imported successfully")

Libraries imported successfully


In [22]:
# load train and test datasets
train=pd.read_csv('datasets/train.csv')
print(train.head(10))   
test=pd.read_csv('datasets/test.csv')


   label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   
5      0       0       0       0       0       0       0       0       0   
6      7       0       0       0       0       0       0       0       0   
7      3       0       0       0       0       0       0       0       0   
8      5       0       0       0       0       0       0       0       0   
9      3       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1      

In [23]:
#parameters and hyper-parameters defined
m=1 #number of training examples
print("No. of examples : {} ".format(m))
num_layer = 3 # number of layers
input_nodes = train.shape[1]-1# number of input nodes, excludes first column 
print("Input nodes : {} ".format(input_nodes))
h1 = 128      # hidden layer 1
h2 = 64       # hidden layer 2
output_nodes = 10 # number of output nodes


No. of examples : 1 
Input nodes : 784 


In [45]:
input=((np.asfarray(train.iloc[3,1:])).reshape(1,784)/ 255.0 * 0.99) + 0.01 

output = np.zeros((m, 10))+ 0.01
for i in range(m):
    output[i, np.array(train.label)[3]] = 0.99
output = output.astype(float)
output=np.transpose(output)
input=np.transpose(input)



In [46]:
print("The size of input is {}.".format(input_nodes))
print("The size of output is {}.".format(output_nodes))
print(input.shape)
print(input)
print("output")
print(output.shape)
print(output)

The size of input is 784.
The size of output is 10.
(784, 1)
[[0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 

In [47]:
#define sigmoid function
def sigmoid(x):
    return 1/(1+np.exp(-x))

def dev_sigmoid(x):
    return np.exp(-x)/(np.square((1+np.exp(-x))))
   

def softmax(z):
        # Numerically stable with large exponentials
        exps = np.exp(z - z.max())
        return exps / (np.sum(exps, axis=0,keepdims=True))

In [48]:
sigmoid(1)
np.tanh(1)

0.7615941559557649

In [49]:
#initialize the required parameters with array of appropriate dimensions
def parameters_initialization(input_nodes, h1, h2, output_nodes):
    
    #weights are initialized in each layer with random values
    W1=np.random.randn(h1,input_nodes)*0.1
    b1=np.zeros((h1,1))
    W2=np.random.randn(h2, h1)*np.sqrt(1./h2)
    b2=np.zeros((h2,1))
    W3=np.random.randn(output_nodes, h2)*0.01
    b3=np.zeros((output_nodes,1))
    
    
    parameters={
        "W1":W1,
        "W2":W2,
        "W3":W3,
        "b1":b1,
        "b2":b2,
        "b3":b3
    }
    
    return parameters
    

In [50]:

parameters=parameters_initialization(input_nodes, h1, h2, output_nodes)
print(parameters['W1'])
print(parameters["W2"])
print(parameters["W3"])

[[ 0.11770229 -0.07914137  0.11982939 ...  0.07485489 -0.08930622
  -0.01222829]
 [ 0.07275774 -0.1057172  -0.06914361 ...  0.19953243  0.07436011
   0.05531574]
 [ 0.35501361  0.05923548  0.01692589 ... -0.02672406  0.10836344
   0.06366608]
 ...
 [-0.02787801  0.08421969 -0.04227845 ... -0.10248847 -0.04217321
  -0.13044079]
 [-0.03077088  0.12400633 -0.07957052 ...  0.06878055  0.13007689
   0.17882676]
 [-0.13098374 -0.0673233   0.19127764 ...  0.08077811  0.06210574
  -0.11237842]]
[[-0.02296119 -0.08570875 -0.06705419 ... -0.14071573 -0.06869187
   0.19842232]
 [ 0.18113992  0.07719225  0.03026872 ...  0.08595497  0.01283136
   0.12416845]
 [ 0.06426687  0.12988253 -0.18136093 ... -0.1252832  -0.01515918
  -0.08605977]
 ...
 [-0.03234437  0.01439601  0.1218308  ...  0.14678459  0.07214387
   0.20493854]
 [-0.07330538 -0.14963877  0.2415719  ... -0.16124048 -0.05844135
  -0.16588068]
 [ 0.03778415  0.34740173  0.26076202 ... -0.23881276 -0.01635914
  -0.03727985]]
[[-2.46395777e-0

In [51]:
def forward_propagation(input,parameters):
    
    
    Z1=np.dot(parameters["W1"],input)+parameters["b1"]
    A1=np.tanh(Z1)
    Z2=np.dot(parameters["W2"],A1)+parameters["b2"]
    A2=np.tanh(Z2)
    Z3=np.dot(parameters["W3"],A2)+parameters["b3"]
    A3=sigmoid(Z3)
    print(A3.shape)
    
    
    cache={
        "A1": A1,
        "A2": A2,
        "A3": A3,
        "Z1": Z1,
        "Z2": Z2,
        "Z3": Z3
        
    }
    

    return A3, cache
    

In [52]:
A3, cache=forward_propagation(input,parameters)
print(cache["A3"])

(10, 1)
[[0.50466513]
 [0.50385413]
 [0.495724  ]
 [0.50062679]
 [0.51167295]
 [0.50771807]
 [0.4863207 ]
 [0.50071839]
 [0.51553809]
 [0.50942409]]


In [53]:
def compute_cost(A2, output, parameters):
    logprobs = np.multiply(np.log(A2),output)
    cost = -np.sum(logprobs)/output.shape[1]
    return cost


In [54]:
def back_propagation(input,output,learning_rate,parameters, cache):
 
    dZ3=cache["A3"]-output
    dW3=np.dot(dZ3,cache["A2"].T)/784
    db3 = np.sum(dZ3, axis=1, keepdims = True)/784
   
    
    dZ2=np.dot(parameters["W3"].T,dZ3)*(1 - np.power(cache["A2"], 2))
    dW2=np.dot(dZ2,cache["A1"].T)/784
    db2 = np.sum(dZ2, axis=1, keepdims = True)/784
    
    
    dZ1=np.dot(parameters["W2"].T,dZ2)*(1 - np.power(cache["A1"], 2))
    dW1=np.dot(dZ1,input.T)
    db1 = np.sum(dZ1, axis=1, keepdims = True)/784
    
    
    
    grads={
        'dW1':dW1,
        'dW2':dW2,
        'dW3':dW3,
        'db1':db1,
        'db2':db2,
        'db3':db3
    }
    

    return grads
    
    

In [55]:
def update_parameters(parameters,grads):
    
    W1 = parameters["W1"]-learning_rate*grads["dW1"]
    b1 = parameters["b1"]-learning_rate*grads["db1"]
    W2 = parameters["W2"]-learning_rate*grads["dW2"]
    b2 = parameters["b2"]-learning_rate*grads["db2"]
    W3 = parameters["W3"]-learning_rate*grads["dW3"]
    b3 = parameters["b3"]-learning_rate*grads["db3"]

    
    parameters = {"W1": W1,
                  "W2": W2,
                  "W3": W3,
                  "b1": b1,
                  "b2": b2,
                  "b3": b3
                }
    
    return parameters

In [56]:
# # 2 - Layer neural network
# def neural_network_model(x_train, y_train,x_test,y_test, num_iterations):
#     cost_list = []
#     index_list = []
#     #initialize parameters and layer sizes
#     parameters = parameters_initialization(x_train, y_train)

#     for i in range(0, num_iterations):
#          # forward propagation
#         A2, cache = forward_propagation(x_train,parameters)
#         # compute cost
#         cost = compute_cost(A2, y_train, parameters)
#          # backward propagation
#         grads = backward_propagatio(parameters, cache, x_train, y_train)
#          # update parameters
#         parameters = update_parameters(parameters, grads)
        
#         if i % 100 == 0:
#             cost_list.append(cost)
#             index_list.append(i)
#             print ("Cost after iteration %i: %f" %(i, cost))
#     plt.plot(index_list,cost_list)
#     plt.xticks(index_list,rotation='vertical')
#     plt.xlabel("Number of Iterarion")
#     plt.ylabel("Cost")
#     plt.show()
    
#     # predict
#     y_prediction_test = predict(parameters,x_test)
#     y_prediction_train = predict(parameters,x_train)

#     # Print train/test Errors
#     print("train accuracy: {} %".format(100 - np.mean(np.abs(y_prediction_train - y_train)) * 100))
#     print("test accuracy: {} %".format(100 - np.mean(np.abs(y_prediction_test - y_test)) * 100))
#     return parameters

# parameters =neural_network_model(x_train, y_train,x_test,y_test, num_iterations=2500)

In [57]:
epochs=2500
learning_rate=0.1
parameters=parameters_initialization(input_nodes, h1, h2, output_nodes)
for epoch in range(0,epochs):
    print("Epoch: "+ str(epoch+1)+"/"+str(epochs))   
    A3,cache=forward_propagation(input,parameters)
    grads=back_propagation(input,output,learning_rate,parameters,cache)
    parameters=update_parameters(parameters,grads)
    print("A3")
    print(cache["A3"])

    
    

Epoch: 1/2500
(10, 1)
A3
[[0.50236593]
 [0.50871877]
 [0.50551895]
 [0.49563128]
 [0.48969561]
 [0.49420207]
 [0.50338886]
 [0.52835251]
 [0.47546659]
 [0.48224851]]
Epoch: 2/2500
(10, 1)
A3
[[0.49987682]
 [0.50581457]
 [0.50347625]
 [0.49240593]
 [0.49097074]
 [0.49264515]
 [0.50164001]
 [0.52508112]
 [0.47414924]
 [0.47829812]]
Epoch: 3/2500
(10, 1)
A3
[[0.49747683]
 [0.50322564]
 [0.50154159]
 [0.48930654]
 [0.49224772]
 [0.49105241]
 [0.49973926]
 [0.52185697]
 [0.47300384]
 [0.47460881]]
Epoch: 4/2500
(10, 1)
A3
[[0.49526054]
 [0.50100877]
 [0.49979526]
 [0.48642156]
 [0.49354834]
 [0.48947321]
 [0.4976201 ]
 [0.51877695]
 [0.47199432]
 [0.47128758]]
Epoch: 5/2500
(10, 1)
A3
[[0.49327573]
 [0.49909522]
 [0.49821843]
 [0.4837233 ]
 [0.49483439]
 [0.48794579]
 [0.49528745]
 [0.51590438]
 [0.47108983]
 [0.46834454]]
Epoch: 6/2500
(10, 1)
A3
[[0.49153148]
 [0.49736671]
 [0.49676082]
 [0.48118925]
 [0.49606643]
 [0.48650306]
 [0.49280974]
 [0.51328976]
 [0.47026735]
 [0.46575594]]
Epoc

In [58]:
test_x =test 